config/routes.rb
require 'sidekiq/web'

VERIFY_USER = lambda do |request|
  return false unless request.session[:user_id]
  user = User.find(request.session[:user_id])
  user.valid_google_user?
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'user/dashboard#show'
  get '/welcome', to: 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/sessions', to: 'sessions#destroy'

  constraints VERIFY_USER do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope module: :user do
    resources :users, only: [:update]
    resources :innings, only: [:show]
    resources :zoom_aliases, only: [:update]
    resources :turing_modules, path: '/modules', only: [:show, :create], shallow: true do
      resources :attendances, only: [:create, :show, :edit, :update, :destroy] do
        resources :populi_transfer, only: [:new, :create, :index]
        patch "students/:id", to: 'attendances#update_zoom_alias', as: :student
        post "retake", to: "attendances#retake", as: "retake"
      end

      

      resources :students

      get '/slack/new', to: 'slack#new', as: :slack_integration
      post '/slack', to: 'slack#create'

      resources :account_match, only: [:new, :create]

      get '/populi/new', to: 'populi#new', as: :populi_integration
      get '/populi/courses/:course_id', to: 'populi#match_students', as: :populi_match_students
      post '/populi', to: 'populi#create'
      patch '/populi', to: 'populi#update'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#show'
    resources :innings, only: [:update, :edit, :new, :create]
    resources :slack_presence_checks, only: [:index]
    resources :reports, only: [:index]
    get "/students/:student_id/report", to: "reports#student", as: "student_report"
  end
end

app/views/shared/_attendance_details.html.erb
<h3>Title: <%= attendance.meeting.title %></h3>
<h3>Date: <%= pretty_date(attendance.attendance_time) %></h3>
<h3>Attendance Time: <%= pretty_time(attendance.attendance_time) %> <%= link_to "Update Attendance Time", edit_attendance_path(attendance) if updatable %></h3>
<p><strong>Present: <%= attendance.count_status(:present) %>, Tardy: <%= attendance.count_status(:tardy) %>, Absent: <%= attendance.count_status(:absent) %></strong></p>
<%= link_to "Transfer Student Attendances to Populi", new_attendance_populi_transfer_path(@attendance) if updatable %>

app/views/shared/_dashboard.html.erb
<section id="module-content">
  <section id='left-column'>
    <section id="turing-module-selection">
      <%= select_tag :turing_module, options_from_collection_for_select(current_inning.turing_modules, :id, :name, mod.id), {id: "turing-module-select"} %>
    </section>
    <% unless current_user.is_this_my_mod?(mod) %>
      <%= button_to 'Set as my Module', user_path(current_user), method: :patch, data: {turbo: false}, params: {turing_module_id: mod.id}, class: 's-button', form_class: "my-mod-button"  %>
    <% end %>
    <% if mod.account_match_complete %>
      <%= link_to "Students (#{mod.students.length})", turing_module_students_path(mod), class: 's-link students-link' %>
      <%= render partial: 'shared/take_attendance', locals: {attendance: Attendance.new, mod: mod} %>
      <h2 id="other-options">Other Options</h2>
      <%= link_to "Redo Module Setup", turing_module_populi_integration_path(mod), class: 's-button danger', id: 'redo-setup' %>
    <% elsif current_user.is_this_my_mod?(mod) %>
      <p><%= link_to "Setup Module", turing_module_populi_integration_path(mod), class: 's-button' %></p>
    <% end %>
  </section>
  <section id='right-column'>
    <%= render partial: 'shared/past_attendances', locals: {attendances: mod.attendances_by_time} %>
  </section>
</section>

app/views/shared/_module_list.html.erb
<% modules.each do |mod| %>
  <section id="turing-module-<%= mod.id %>" class="module">
    <h3><%= link_to mod.name, turing_module_path(mod) %></h3>
  </section>
<% end %>

app/views/shared/_past_attendances.html.erb
<section id='past-attendances'>  
  <h3 class='s-h3'>Past Attendances</h3>
  <table>
    <tr>
      <th>Meeting Title</th>
      <th>Attendance Time</th>
    </tr>
    <% attendances.each do |attendance| %>
      <tr id='attendance-<%= attendance.id %>', class='attendance'>
        <td><%= link_to attendance.meeting.title, attendance_path(attendance) %></td>
        <td><%= pretty_time(attendance.attendance_time) %> - <%= pretty_date(attendance.attendance_time) %></td>
      </tr>
    <% end %>
  </table>
</section>

app/views/shared/_slack_attendance_table.html.erb
<h3>Type: Slack Thread</h3>
<h3>Thread Link: <%= link_to facade.thread_link, facade.thread_link %></h3>
<h3>Date: <%= facade.attendance_date %></h3>
<h3>Attendance Time: <%= facade.attendance_time %> <%= link_to "Update Attendance Time", edit_attendance_path(facade.attendance) if facade.updatable %></h3>
<p><strong>Present: <%= facade.status_count(:present) %>, Tardy: <%= facade.status_count(:tardy) %>, Absent: <%= facade.status_count(:absent) %></strong></p>
<%= link_to "Transfer Student Attendances to Populi", new_attendance_populi_transfer_path(facade.attendance) if facade.updatable %>

<table id='student-attendances' class="sortable">
  <thead>
    <tr>
      <th>Student</th>
      <th>Join Time</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% facade.student_attendances.each do |student_attendance| %>
      <tr id='student-attendance-<%= student_attendance.id %>' class='student-attendance'>
        <section id='student-<%= student_attendance.student.id %>'>
          <td><%= link_to student_attendance.student.name, student_path(student_attendance.student) %></td>
          <% if student_attendance.join_time %>
            <td><%= pretty_time(student_attendance.join_time) %></td>
          <% else %>
            <td>N/A</td>
          <% end %>
          <td class='<%= student_attendance.status %>'><%= student_attendance.status %></td>
        </section>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_take_attendance.html.erb
<section id='take-attendance'>
  <h2>Take Attendance for a Slack or Zoom Meeting</h2>
  <%= form_with model: [mod, attendance], id: 'take-attendance', data: {turbo: false} do |f| %>
    <p class='s-p'>
      <%= f.label :meeting_url, "Enter the Zoom or Slack Link" %>
      <%= f.text_field :meeting_url %>
    </p>
    <%= f.submit 'Take Attendance', class: 's-button' %>
  <% end %>
</section>

app/views/shared/_zoom_attendance_table.html.erb
<h3>Title: <%= facade.meeting_title %></h3>
<h3>Type: Zoom Meeting</h3>
<h3>Meeting ID: <%= facade.meeting_id %></h3>
<h3>Date: <%= facade.attendance_date %></h3>
<h3>Attendance Time: <%= facade.attendance_time %> <%= link_to "Update Attendance Time", edit_attendance_path(facade.attendance) if facade.updatable %></h3>
<p><strong>Present: <%= facade.status_count(:present) %>, Tardy: <%= facade.status_count(:tardy) %>, Absent: <%= facade.status_count(:absent) %></strong></p>
<%= link_to "Transfer Student Attendances to Populi", new_attendance_populi_transfer_path(facade.attendance) if facade.updatable %>

<p>Use the zoom alias fields to correct student attendances</p>
<table id='student-attendances' class="sortable">
  <thead>
    <tr>
      <th>Student</th>
      <th>Join Time</th>
      <th>Status</th>
      <th>Duration (minutes)</th>
      <th>Zoom Aliases Used</th>
      <th>Save a new Zoom Alias</th>
    </tr>
  </thead>
  <tbody>
    <% facade.student_attendances.each do |student_attendance| %>
      <tr id='student-attendance-<%= student_attendance.id %>' class='student-attendance'>
        <section id='student-<%= student_attendance.student.id %>'>
          <td><%= link_to student_attendance.student.name, student_path(student_attendance.student) %></td>
          <% if student_attendance.join_time %>
            <td><%= pretty_time(student_attendance.join_time) %></td>
          <% else %>
            <td>N/A</td>
          <% end %>
          <td class='<%= student_attendance.status %>'><%= student_attendance.status %></td>
          <td class='duration'><%= student_attendance.duration %></td>
          <td class="alias-used">
            <%= student_attendance.student.zoom_alias_names.to_sentence %>
            <%= link_to "Edit", student_path(student_attendance.student), class: "s-button danger alias-correction" %>
          </td>
          <td id='student-aliases-<%= student_attendance.student.id %>'>
            <%= form_with model: [@attendance, student_attendance.student], class: "alias-correction" do |f| %>
              <%= f.select :zoom_alias, facade.alias_options_for(student_attendance.student), {}, class: "alias-correction" %>
              <%= f.submit "Save Zoom Alias", class: "s-button alias-correction" %>
            <% end %>
          </td>
        </section>
      </tr>
    <% end %>
  </tbody>
</table>