config/routes.rb
require 'sidekiq/web'

VERIFY_USER = lambda do |request|
  return false unless request.session[:user_id]
  user = User.find(request.session[:user_id])
  user.valid_google_user?
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'user/dashboard#show'
  get '/welcome', to: 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/sessions', to: 'sessions#destroy'

  constraints VERIFY_USER do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope module: :user do
    resources :users, only: [:update]
    resources :innings, only: [:show]
    resources :zoom_aliases, only: [:update]
    resources :turing_modules, path: '/modules', only: [:show, :create], shallow: true do
      resources :attendances, only: [:create, :show, :edit, :update, :destroy] do
        resources :populi_transfer, only: [:new, :create, :index]
        patch "students/:id", to: 'attendances#update_zoom_alias', as: :student
        post "retake", to: "attendances#retake", as: "retake"
      end

      

      resources :students

      get '/slack/new', to: 'slack#new', as: :slack_integration
      post '/slack', to: 'slack#create'

      resources :account_match, only: [:new, :create]

      get '/populi/new', to: 'populi#new', as: :populi_integration
      get '/populi/courses/:course_id', to: 'populi#match_students', as: :populi_match_students
      post '/populi', to: 'populi#create'
      patch '/populi', to: 'populi#update'
    end
  end

  namespace :admin do
    get '/', to: 'dashboard#show'
    resources :innings, only: [:update, :edit, :new, :create]
    resources :slack_presence_checks, only: [:index]
    resources :reports, only: [:index]
    get "/students/:student_id/report", to: "reports#student", as: "student_report"
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController
  include ApplicationHelper
  require 'csv'

  def index
    @students = Inning.find_by(current: true).students
  end

  def student
    @student = Student.find(params[:student_id])
    if params[:start_date] && params[:end_date]
      @student_attendance_hours = @student.report(params[:start_date], params[:end_date])
    end

    respond_to do |format|
      format.html
      format.csv do
        send_data student_csv_report(@student_attendance_hours), 
            type: 'text/csv; charset=utf-8; header=present', 
            filename: "#{@student.name}-#{params[:start_date]}-to-#{params[:end_date]}.csv"
      end
    end
  end

  private 
  def student_csv_report(attendance_hours)
    csv_data = CSV.generate(headers: true) do |csv|
      csv << ["Status","Potential Minutes", "Active Minutes","Date","Start","End","Type","Check Method"]
      attendance_hours.each do |hour|
        csv << [hour.status, hour.potential_minutes, hour.duration, "#{short_date(hour.start)}",  "#{pretty_time(hour.start)}", "#{pretty_time(hour.end_time)}", hour.attendance_type, hour.check_method]
      end
    end
    return csv_data
  end
end

app/views/admin/reports/index.html.erb
<h2>Current Inning Students</h2>
<% @students.each do |student| %>
  <p><%= link_to student.name, admin_student_report_path(student) %></p>
<% end %>

app/views/admin/reports/student.html.erb
<h1>Reporting for <%= @student.name %></h1>
<h2>Select Date Range for Report</h2>
<%= form_with method: :get do |f| %>
  <%= f.label "Start Date" %>
  <%= f.date_field :start_date %>
  <%= f.label "End Date" %>
  <%= f.date_field :end_date %>
  <%= f.submit "Generate Report" %>
<% end %>

<% if @student_attendance_hours %>
<section id="report">
    <h2><%= @student.name %>: <%= params[:start_date] %> to <%= params[:end_date] %></h2>
    <section id="summary">
      <h3>Summary</h3>
      <p><strong>Credit Hours Eligible: <%= @student_attendance_hours.total.in_hours %></strong></p>
      <p><strong>Credit Hours Earned: <%= @student_attendance_hours.total(status: :present).in_hours %></strong></p>
      <p><strong>Lesson Hours Eligible: <%= @student_attendance_hours.total(meeting_type: "ZoomMeeting").in_hours %></strong></p>
      <p><strong>Lesson Hours Earned: <%= @student_attendance_hours.total(status: :present, meeting_type: "ZoomMeeting").in_hours %></strong></p>
      <p><strong>Lab Hours Eligible: <%= @student_attendance_hours.total(meeting_type: "SlackThread").in_hours %></strong></p>
      <p><strong>Lab Hours Earned: <%= @student_attendance_hours.total(status: :present, meeting_type: "SlackThread").in_hours %></strong></p>
    </section>

    <section id="attendance-hours">
      <h3>Attendance Hours</h3>
      <%= link_to "Download as CSV", url_for(params: request.query_parameters, format: :csv) %>
      <table class="sortable s-table">
        <thead>
          <tr>
              <th>Date</th>
              <th>Start</th>
              <th>End</th>
              <th>Status</th>
              <th>Potential Minutes</th>
              <th>Active Minutes</th>
              <th>Type</th>
              <th>Check Method</th>
          </tr>
        </thead>
        <tbody>
          <% @student_attendance_hours.each do |hour| %>
            <tr>
              <td><%= short_date(hour.start) %></td>
              <td><%= pretty_time(hour.start) %></td>
              <td><%= pretty_time(hour.end_time) %></td>
              <td><%= hour.status %></td>
              <td><%= hour.potential_minutes %></td>
              <td><%= hour.duration %></td>
              <td><%= hour.attendance_type %></td>
              <td><%= hour.check_method %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  </section>
<% end %>